name: work_manager
description: Work Manager

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  path_provider: ^1.2.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  workmanager: ^0.2.3
  shared_preferences:
  flutter_local_notifications: ^4.0.1+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
